# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
from tensorflow.keras import datasets

In [3]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
x_test.shape

(10000, 28, 28)

In [8]:
width, height = 28, 28
input_shape = (width, height, 1)

In [9]:
input_shape

(28, 28, 1)

In [10]:
x_train = x_train.reshape(x_train.shape[0], width, height, 1)
x_test = x_test.reshape(x_test.shape[0], width, height, 1)

In [11]:
x_train.shape

(60000, 28, 28, 1)

In [12]:
x_test.shape

(10000, 28, 28, 1)

In [13]:
y_train.shape

(60000,)

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1)

In [15]:
len(x_train)

54000

In [16]:
len(x_val)

6000

In [17]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val= (x_val - x_val.mean()) / x_val.std()
x_test= (x_test - x_test.mean()) / x_test.std()

In [18]:
from tensorflow  import keras

In [19]:
num_labels = 10
y_train = keras.utils.to_categorical(y_train)

In [20]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

# Model

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

In [28]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5,5), strides = (1,1), activation = 'tanh', input_shape  = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2, 2), strides=(2, 2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))


model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation='softmax'))

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_4 (Averag  (None, 23, 23, 6)        0         
 ePooling2D)                                                     
                                                                 
 conv2d_7 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_5 (Averag  (None, 9, 9, 16)         0         
 ePooling2D)                                                     
                                                                 
 conv2d_8 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten_1 (Flatten)         (None, 3000)             

In [32]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [34]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data  = (x_val, y_val))

Epoch 1/20
1688/1688 [==============================] - 20s 12ms/step - loss: 0.1922 - accuracy: 0.9425 - val_loss: 0.0924 - val_accuracy: 0.9730
Epoch 2/20
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0920 - accuracy: 0.9723 - val_loss: 0.0813 - val_accuracy: 0.9757
Epoch 3/20
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0784 - accuracy: 0.9759 - val_loss: 0.0799 - val_accuracy: 0.9763
Epoch 4/20
1688/1688 [==============================] - 20s 12ms/step - loss: 0.0713 - accuracy: 0.9781 - val_loss: 0.0784 - val_accuracy: 0.9742
Epoch 5/20
1688/1688 [==============================] - 19s 11ms/step - loss: 0.0670 - accuracy: 0.9787 - val_loss: 0.0622 - val_accuracy: 0.9828
Epoch 6/20
1688/1688 [==============================] - 18s 11ms/step - loss: 0.0615 - accuracy: 0.9812 - val_loss: 0.0554 - val_accuracy: 0.9830
Epoch 7/20
1688/1688 [==============================] - 19s 11ms/step - loss: 0.0584 - accuracy: 0.9819 - val_loss: 0.0618 -

In [36]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 2s 5ms/step - loss: 0.0496 - accuracy: 0.9848


In [38]:
score

[0.04961680248379707, 0.9847999811172485]